Create database address;
use address;

CREATE TABLE person (
	SIN BIGINT PRIMARY KEY,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30) NOT NULL
	);

CREATE TABLE address (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PERSON_SIN BIGINT NOT NULL, 
	DATE_FROM DATE NOT NULL,
	DATE_TO DATE NOT NULL,
	STREET_NUMBER BIGINT NOT NULL,
	STREET_ADDRESS VARCHAR(50) NOT NULL,
	CITY VARCHAR(30) NOT NULL,
	PROVINCE CHAR(2) NOT NULL,
	POSTAL_CODE CHAR(6) NOT NULL,
	COUNTRY VARCHAR(10) NOT NULL

	);


ALTER TABLE address ADD CONSTRAINT PERSON_FK FOREIGN KEY (person_sin)
	REFERENCES person(SIN)	ON DELETE RESTRICT;


